
def generate_values(x: float, y: float):
    '''
        Returns list of possible values that can be generated by arithmetic combination b/w x & y
    '''

    st = [x+y, y-x, x-y, x*y]
    if (x != 0):        
        st.append(y/x)

    if (y != 0):
        st.append(x/y)

    return st


def base_solver(target: float, hand: tuple[int]):
    '''
        target: Number to make using given hand
        hand: Tuple of 2 integers

        Returns True if possible to compute target; False otherwise
    '''
    assert(len(hand) == 2)

    return target in generate_values(hand[0], hand[1])


def solver(target: float, hand: tuple[int], cache: dict):
    ''' 
        target: Number to make
        hand: Tuple of any amount of integers
        cache: store results of subproblems to avoid recomputation

        Returns True if possible to compute target, False otherwise
    '''
    
    if (target, hand) in cache:
        return cache[(target, hand)]
    
    if target in hand:
        cache[(target, hand)] = True
        return True
    
    N = len(hand)

    if (N == 2):
        cache[(target, hand)] = base_solver(target, hand)
        return cache[(target, hand)]

    for i in range(N):
        for j in range(i+1, N):
            oth = [hand[k] for k in range(N) if k not in (i, j)]
            x, y = hand[i], hand[j]

            ops = generate_values(x, y)

            if target in ops:
                return True
        
            for op in ops:
                candidate = tuple(oth + [op])
                rst = solver(target, candidate, cache)
                cache[(target, candidate)] = rst

                if rst:
                    return True
                
    return False
    
